In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [10]:
# simple example
import numpy as np
from sklearn.linear_model import LinearRegression

# Sample input data
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2, 4, 6, 8, 10])

# Create a Linear Regression model
model = LinearRegression()

# Fit the model to the data
model.fit(X, y)

# Predict using the trained model
X_new = np.array([[6], [7], [8]])
y_pred = model.predict(X_new)

print(y_pred)


[12. 14. 16.]


In [13]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

# Sample input data with a categorical column
X = np.array([[1, 'A'], [2, 'B'], [3, 'A'], [4, 'C'], [5, 'B']])
y = np.array([20, 40, 60, 80, 100])

# Convert categorical column to numeric values
X[:, 1] = np.unique(X[:, 1], return_inverse=True)[1]
# X[:,1] selects column of array X

#np.unique(X[:, 1], return_inverse=True):

#This function call returns two arrays. 
#The first array contains the unique values from column 1 of X, 
#and the second array contains the indices that map each element in column 1 to its corresponding unique value.
#By setting return_inverse=True, 
#we instruct the function to return the inverse mapping, which gives us the indices that represent each element in column 1.

#[1]: This indexing operation selects the second array returned by np.unique(),

#which contains the indices representing the categorical values in column 1.
# Create a ColumnTransformer to one-hot encode the categorical column

# X[:, 1] = ...: This assigns the values from the second array (the indices) to column 1 of X,

#effectively replacing the categorical values with their corresponding numeric representations.
# ct = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')

# X_encoded = ct.fit_transform(X)

# Create a Linear Regression model
model = LinearRegression()

# Fit the model to the encoded data
model.fit(X_encoded, y)

# Convert new input data categorical column to numeric values
X_new = np.array([[6, 'A'], [7, 'B'], [8, 'C']])
X_new[:, 1] = np.unique(X_new[:, 1], return_inverse=True)[1]

# Predict using the trained model
X_new_encoded = ct.transform(X_new)
y_pred = model.predict(X_new_encoded)

print(y_pred)

[120. 140. 160.]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:964: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


In [14]:
import numpy as np

# Sample input data
X = np.array([[1, 'A'], [2, 'B'], [3, 'A'], [4, 'C'], [5, 'B']])
y = np.array([2, 4, 6, 8, 10])

# Convert categorical column to numeric values
X[:, 1] = np.unique(X[:, 1], return_inverse=True)[1]

# Combine X and y horizontally
data = np.hstack((X, y.reshape(-1, 1)))

# Save data to a CSV file
np.savetxt('data.csv', data, delimiter=',', fmt='%s')

In [17]:
a=pd.read_csv('data.csv')

In [18]:
a

1  0   2
0  2  1   4
1  3  0   6
2  4  2   8
3  5  1  10

In [44]:
from sklearn.preprocessing import LabelEncoder

a = ['a', 'b', 'c', 'b']
b = ['a', 'b', 'c', 'bb','e']
c = ['a', 'b', 'eee', 'bb','e']


# Create an instance of LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the list 'a'
a_encoded = label_encoder.fit_transform(a)


print(a_encoded)
b_encoded = label_encoder.fit_transform(b)
print(b_encoded)

c_encoded = label_encoder.fit_transform(c) # size bigger means value will be valued last
print(c_encoded)



[0 1 2 1]
[0 1 3 2 4]
[0 1 4 2 3]


[0 1 3 2 4]
