In [1]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
np.random.seed(0)

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [3]:
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [17]:
df['is_train']=np.random.uniform(0,1,len(df))<=.75 #generating random number between 0 and 1 to all rows-len(df) if its less than 
                                                    #0.75 is_train is true else flase 
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa     False  
2  setosa      True  
3  setosa      True  
4  setosa     False

In [18]:
train=df[df['is_train']==True]
test=df[df['is_train']==False]
print("length of train ",len(train))
print("length of test ",len(test))

length of train  113
length of test  37


In [24]:
features=df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [21]:
#converting each species name into digits
y=pd.factorize(train['species'])[0]
y  #0,1,2-types of species

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2], dtype=int64)

In [26]:
clf=RandomForestClassifier(n_jobs=2,random_state=0)  # n_jobs number of priorities
clf.fit(train[features],y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [27]:

clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [29]:

clf.predict_proba(test[features])[10:20]

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.99, 0.01],
       [0.  , 0.99, 0.01],
       [0.  , 0.05, 0.95],
       [0.  , 0.99, 0.01],
       [0.  , 1.  , 0.  ]])

In [31]:
pred=iris.target_names[clf.predict(test[features])]

In [39]:
pred[0:25]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'virginica', 'virginica', 'virginica'], dtype='<U10')

In [38]:
df[0:25]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
5                 5.4               3.9                1.7               0.4   
6                 4.6               3.4                1.4               0.3   
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
9                 4.9               3.1                1.5               0.1   
10                5.4               3.7                1.5               0.2   
11                4.8               3.4                1.6               0.2   
12                4.8               3.0                1.4               0.1   
13                4.3               3.0                1.1               0.1   
14                5.8               4.0                1.2               0.2   
15                5.7               4.4                1.5               0.4   
16                5.4               3.9                1.3               0.4   
17                5.1               3.5                1.4               0.3   
18                5.7               3.8                1.7               0.3   
19                5.1               3.8                1.5               0.3   
20                5.4               3.4                1.7               0.2   
21                5.1               3.7                1.5               0.4   
22                4.6               3.6                1.0               0.2   
23                5.1               3.3                1.7               0.5   
24                4.8               3.4                1.9               0.2   

   species  is_train  
0   setosa      True  
1   setosa     False  
2   setosa      True  
3   setosa      True  
4   setosa     False  
5   setosa      True  
6   setosa      True  
7   setosa      True  
8   setosa      True  
9   setosa     False  
10  setosa      True  
11  setosa      True  
12  setosa      True  
13  setosa      True  
14  setosa      True  
15  setosa      True  
16  setosa      True  
17  setosa      True  
18  setosa     False  
19  setosa      True  
20  setosa      True  
21  setosa     False  
22  setosa      True  
23  setosa     False  
24  setosa     False

In [40]:
test['species'].head()

1     setosa
4     setosa
9     setosa
18    setosa
21    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [42]:

pd.crosstab(test['species'],pred,rownames=['Actual species'],colnames=['predicted'])

predicted       setosa  versicolor  virginica
Actual species                               
setosa              13           0          0
versicolor           0           7          1
virginica            0           1         15